### ISSUE TITLE
Angular 22 chunk optimization still corrupts shared externals

### ISSUE THREAD

**Issue by dr460nf1r3** [native-federation/angular-adapter#107]
#72 is seemingly not entirely fixed in the latest version. Here this still seems to happen if I understand correctly. The fact that I get an `ɵɵdefineService` error in production builds (as opposed to the component above) and that setting the env during build time fixes it makes me believe it is the case. Besides turning off optimization entirely also fixes the issue.

Error in prod: 
```
typeError: t.ɵɵdefineService is not a function
    at <static_initializer> (chunk-DRel_GHB.js:4:14753)
    at chunk-DRel_GHB.js:4:13917
    at chunk-DRel_GHB.js:4:14823
```

Sample build sample files with no env set: 
```
-rw-r--r--   1 nijen staff    61254 Jul 29 16:11 chunk-BAKmRvmB.js
-rw-r--r--   1 nijen staff    71126 Jul 29 16:11 chunk-BLxD3zW8.js
-rw-r--r--   1 nijen staff   409971 Jul 29 16:11 chunk-BSWShLEb.js
-rw-r--r--   1 nijen staff     2936 Jul 29 16:11 chunk-BfBYYfqt.js
-rw-r--r--   1 nijen staff   108575 Jul 29 16:11 chunk-BgXkgfjM.js
-rw-r--r--   1 nijen staff     8564 Jul 29 16:11 chunk-C-rXaqam.js
-rw-r--r--   1 nijen staff    75678 Jul 29 16:11 chunk-CQOlNMmw.js
-rw-r--r--   1 nijen staff  1083062 Jul 29 16:11 chunk-CV4TgImQ.js
-rw-r--r--   1 nijen staff     3077 Jul 29 16:11 chunk-CYArbaVx.js
-rw-r--r--   1 nijen staff     2442 Jul 29 16:11 chunk-ClxdHx00.js
-rw-r--r--   1 nijen staff    73159 Jul 29 16:11 chunk-CmsJGRGt.js
-rw-r--r--   1 nijen staff  1937702 Jul 29 16:11 chunk-CyUdXsnP.js
-rw-r--r--   1 nijen staff     8716 Jul 29 16:11 chunk-D-iGuZ4z.js
-rw-r--r--   1 nijen staff    17932 Jul 29 16:11 chunk-D4hMdsc0.js
-rw-r--r--   1 nijen staff   182400 Jul 29 16:11 chunk-DBY-6WfD.js
-rw-r--r--   1 nijen staff     3155 Jul 29 16:11 chunk-DKE9qkuO.js
-rw-r--r--   1 nijen staff     7877 Jul 29 16:11 chunk-DWgmysyv.js
-rw-r--r--   1 nijen staff    81464 Jul 29 16:11 chunk-DZoRqOns.js
-rw-r--r--   1 nijen staff    19768 Jul 29 16:11 chunk-DcNmA6hY.js
-rw-r--r--   1 nijen staff     5494 Jul 29 16:11 chunk-DeK22HLJ.js
-rw-r--r--   1 nijen staff    12177 Jul 29 16:11 chunk-Dgdq1dvA.js
-rw-r--r--   1 nijen staff     4748 Jul 29 16:11 chunk-DqcN9uR6.js
```

with variable set explicitly:
```
-rw-r--r--  1 nijen staff    2167 Jul 29 16:27 chunk-LTVOGC3Y.js
-rw-r--r--  1 nijen staff  274752 Jul 29 16:27 chunk-LZKY23CD.js
-rw-r--r--  1 nijen staff   74984 Jul 29 16:27 chunk-M22IPLYB.js
-rw-r--r--  1 nijen staff    3116 Jul 29 16:26 chunk-MG4QGYYZ.js
-rw-r--r--  1 nijen staff    3026 Jul 29 16:27 chunk-MMXODR4X.js
-rw-r--r--  1 nijen staff 1694085 Jul 29 16:27 chunk-PFBS7E6K.js
-rw-r--r--  1 nijen staff    2777 Jul 29 16:27 chunk-PTB33LOL.js
-rw-r--r--  1 nijen staff    1750 Jul 29 16:26 chunk-PZNONLPT.js
-rw-r--r--  1 nijen staff  108115 Jul 29 16:27 chunk-QWUWXNGU.js
-rw-r--r--  1 nijen staff   70866 Jul 29 16:27 chunk-S4QPNL5Y.js
-rw-r--r--  1 nijen staff   11375 Jul 29 16:27 chunk-S6B6RIUT.js
-rw-r--r--  1 nijen staff   56066 Jul 29 16:27 chunk-S7FCZWSL.js
-rw-r--r--  1 nijen staff    1682 Jul 29 16:27 chunk-TMBDFVLK.js
-rw-r--r--  1 nijen staff    5757 Jul 29 16:27 chunk-TNKXNVBG.js
-rw-r--r--  1 nijen staff    9894 Jul 29 16:27 chunk-TNLA2KMU.js
-rw-r--r--  1 nijen staff   81383 Jul 29 16:27 chunk-TRCZMJHZ.js
-rw-r--r--  1 nijen staff    8355 Jul 29 16:27 chunk-V7L4JJSU.js
-rw-r--r--  1 nijen staff   17955 Jul 29 16:27 chunk-V7LNCRHH.js
-rw-r--r--  1 nijen staff  408716 Jul 29 16:27 chunk-VYKMNCBK.js
-rw-r--r--  1 nijen staff   49602 Jul 29 16:26 chunk-WNFK3WQ6.js
-rw-r--r--  1 nijen staff     703 Jul 29 16:26 chunk-XLSTF3FT.js
-rw-r--r--  1 nijen staff     603 Jul 29 16:27 chunk-Y5WBWCBW.js
```

I suppose these always look like this?
```
-rw-r--r--  1 nijen staff   80139 Jul 29 16:26 _angular_common.O1z_Q1E7fj.js
-rw-r--r--  1 nijen staff   48077 Jul 29 16:26 _angular_common_http.gitxwnnFzU.js
-rw-r--r--  1 nijen staff    2291 Jul 29 16:26 _angular_common_locales_de.QzWZlQEKsi.js
-rw-r--r--  1 nijen staff    1464 Jul 29 16:26 _angular_common_locales_en.nalRqdEVyA.js
-rw-r--r--  1 nijen staff  377400 Jul 29 16:26 _angular_core.kUUiHpimVl.js
-rw-r--r--  1 nijen staff     661 Jul 29 16:26 _angular_core_primitives_di.yHhtwYT1qJ.js
-rw-r--r--  1 nijen staff    4403 Jul 29 16:26 _angular_core_primitives_signals.QT1-1fvrKr.js
-rw-r--r--  1 nijen staff    3680 Jul 29 16:26 _angular_core_rxjs_interop.j5j5JBYmT7.js
-rw-r--r--  1 nijen staff   83262 Jul 29 16:26 _angular_forms.crE4F_3Xf7.js
-rw-r--r--  1 nijen staff   26174 Jul 29 16:26 _angular_platform_browser.MVmAec8-Pb.js
-rw-r--r--  1 nijen staff  120107 Jul 29 16:26 _angular_router.MlgxWjt1N6.js
-rw-r--r--  1 nijen staff   30447 Jul 29 16:26 _jsverse_transloco.OqmTMejTEp.js
```

Federation config: 
```
import { share, withNativeFederation } from '@angular-architects/native-federation/config';

export default withNativeFederation({
  name: 'shell',

  shared: {
    ...share({
      '@angular/core': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
        includeSecondaries: { keepAll: true },
      },
      '@angular/common': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
        includeSecondaries: { keepAll: true },
      },
      '@angular/common/http': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@angular/common/locales/de': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@angular/common/locales/en': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@angular/router': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@angular/forms': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@angular/platform-browser': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@angular/platform-browser-dynamic': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      '@jsverse/transloco': {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
      rxjs: {
        singleton: true,
        strictVersion: true,
        requiredVersion: 'auto',
      },
    }),
  },

  sharedMappings: ['somelib'],

  features: {
    ignoreUnusedDeps: true,
  },
});
```

Relevant versions in use:
```
    "@angular-architects/native-federation": "^22.0.6",
    "@angular-devkit/core": "22.0.7",
    "@angular-devkit/schematics": "22.0.7",
    "@angular/animations": "22.0.8",
    "@angular/cdk": "22.0.5",
    "@angular/common": "22.0.8",
    "@angular/compiler": "22.0.8",
    "@angular/core": "22.0.8",
    "@angular/forms": "22.0.8",
    "@angular/platform-browser": "22.0.8",
    "@angular/router": "22.0.8",
    "@softarc/native-federation": "~4.3.2",
    "@softarc/native-federation-orchestrator": "^4.2.2",
```

**Comment by Aukevanoost** [comment]
Hi @dr460nf1r3! thanks again, I did some digging

This isn't the import map going out of sync (that was my theory in #73, and it turns out to be wrong — the import map and remoteEntry come out byte-identical either way). It's an upstream bug in Angular's chunk optimizer: [angular/angular-cli#33583](https://github.com/angular/angular-cli/issues/33583). When it re-bundles, it can end up giving the @angular/core namespace import and a class the same short name:

```
import * as e from '@angular/core';
let e$1 = class e {
  static ɵcmp = e.ɵɵdefineComponent({ type: e }); // e is the class here, not the namespace
};
```

A named class expression binds its own name inside the class body, so the static initializer calls the method on the class instead of the namespace and you get ... is not a function. Yours lands on ɵɵdefineService rather than ɵɵdefineComponent, but it's the same mechanism. It only surfaces when a framework package is external, which is why federation runs into it and plain Angular apps don't.

What I don't understand yet is why our builder didn't disable the BUILD_OPTIMIZE_CHUNKS=0, and I've confirmed that still works on 22.0.6.

**Comment by Aukevanoost** [comment]
I am wondering, is there a way for you to check in your Angular build if the `NG_BUILD_OPTIMIZE_CHUNKS` environment variable is set to "infinity" or "0"? That would help a ton. 

A console.log in `./node_modules/@angular/build/src/utils/environment-options.js` ([src](https://github.com/angular/angular-cli/blob/3039776d9b598b55f04a188fab9a271969fe46c4/packages/angular/build/src/utils/environment-options.ts#L168)) would be enough right before the "undefined" check

Thanks a bunch in advance

**Comment by dr460nf1r3** [comment]
Here are the logs you requested:
```
 INFO  Removed unused dependencies.
 INFO  Building federation artifacts
 NOTE  Skip packages you don't want to share in your federation config
 INFO  Bundling external npm packages with bundle type 'browser-shared'
0

0
"IterableDiffers", "INJECTOR", "runInInjectionContext" and "SkipSelf" are imported from external module "@angular/core" but never used in "chunk-ALFNZMWI.js" and "chunk-YF2HQLHB.js".
"asapScheduler" is imported from external module "rxjs" but never used in "chunk-ALFNZMWI.js".
"pairwise", "shareReplay" and "takeWhile" are imported from external module "rxjs/operators" but never used in "chunk-ALFNZMWI.js" and "chunk-YF2HQLHB.js".
Initial chunk files   | Names                        |  Raw size | Estimated transfer size
```
I guess that confirms it is set to 0.

**Comment by Aukevanoost** [comment]
Interesting, so that is not the issue. Could be stale chunks/externals? I'll see if i can do some more digging soon. 

Anyway it apparently does have something to do with optimization since 

> Besides turning off optimization entirely also fixes the issue.

**Comment by ChristianLoosliVGT** [comment]
I have the same problem and have also described it in an Angular CLI ticket https://github.com/angular/angular-cli/issues/33583. Does that mean the only workaround right now is to set NG_BUILD_OPTIMIZE_CHUNKS=0?

**Comment by Aukevanoost** [comment]
@ChristianLoosliVGT 

For the chunk rewrite AFAIK yes, the real question is whether this is an issue.
1. Angular baked the new feature deep in the builder, so no access for us during the "remote build" which is using the ESbuild plugin (the esbuild plugin is not using the chunk optimization, only the main builder). Therefore we cannot use it even if we wanted to.
2. Our dependency sharing mechanism is noticably different than Angular. We externalize most of the final code (from the dependencies we share), which makes the remote bundles a lot smaller (thus the benefit is a lot less noticable). I can imagine with a normal SPA, you want to optimize the exported code as much as possible, that is less of an issue when all the dependencies are externalized. 

it would be cool though if we would get access to the chunk optimization. But I don't think it makes sense from the Angular team's perspective to expose it since that increases maintainability and disallows them to tweak/update it between minors. They try to keep the exposed interface as slim as possible.

**Comment by ChristianLoosliVGT** [comment]
So, does that mean you'll keep looking for a solution, or what do you think I should do?

**Comment by Aukevanoost** [comment]
Well depends, if `NG_BUILD_OPTIMIZE_CHUNKS=0` fixes the issue, good! We already disable it by default now so no action needed. 
if it doesn't fix the issue (which is the case here), I'll have to dig into what is causing this chunk rewrite. 

I did see you mention the `NG_BUILD_MANGLE=0` as second env variable for solving the issue? Might be a lead, haven't had the time to dig into this fully. But for the time being this might be a nice addition?

**Comment by ChristianLoosliVGT** [comment]
NG_BUILD_MANGLE=0: Yes, but then the main bundle is a bit larger. 

In which version did you set NG_BUILD_OPTIMIZE_CHUNKS=0?

**Comment by Aukevanoost** [comment]
https://github.com/native-federation/angular-adapter/releases/tag/v22.0.3

**Comment by ChristianLoosliVGT** [comment]
the builder-level env override is ineffective when building through Nx. :(

**Comment by dr460nf1r3** [comment]
> the builder-level env override is ineffective when building through Nx. :(

That would explain a lot, we also build via nx.

**Comment by Aukevanoost** [comment]
I did some digging and it's beyond our control since NX loads everything up before we can set the env variables. I expanded the feature to rewrite the variables at runtime. It's not pretty but right now it's all we got. @ Let me know if it fixes your issues.

**Comment by ChristianLoosliVGT** [comment]
Perfect, so you deploy a new version of the lib today?

**Comment by Aukevanoost** [comment]
If all goes well, tomorrow. But I can setup a RC

**Comment by Aukevanoost** [comment]
https://github.com/native-federation/angular-adapter/releases/tag/v22.1.0-RC1
